/*
 * Copyright (c) 2022-2024. Ryan Wong (hello@ryanwebmail.com)
 */

package uk.ryanwong.gmap2ics.ui.theme.japanesepurple

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8B4484)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F5)
val md_theme_light_onPrimaryContainer = Color(0xFF380037)
val md_theme_light_secondary = Color(0xFF6E5869)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF7DAEE)
val md_theme_light_onSecondaryContainer = Color(0xFF271624)
val md_theme_light_tertiary = Color(0xFF815345)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onTertiaryContainer = Color(0xFF321208)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEEDEE7)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFABF2)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8B4484)

val md_theme_dark_primary = Color(0xFFFFABF2)
val md_theme_dark_onPrimary = Color(0xFF551352)
val md_theme_dark_primaryContainer = Color(0xFF6F2C6B)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F5)
val md_theme_dark_secondary = Color(0xFFDABFD2)
val md_theme_dark_onSecondary = Color(0xFF3D2B3A)
val md_theme_dark_secondaryContainer = Color(0xFF554150)
val md_theme_dark_onSecondaryContainer = Color(0xFFF7DAEE)
val md_theme_dark_tertiary = Color(0xFFF5B8A7)
val md_theme_dark_onTertiary = Color(0xFF4C261A)
val md_theme_dark_tertiaryContainer = Color(0xFF663C2F)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C2CB)
val md_theme_dark_outline = Color(0xFF9A8D95)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFF8B4484)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFABF2)

val seed = Color(0xFFB3256)
