name: KMP CI

on:
  pull_request:
    branches: [ "main", 'renovate/**', 'feature/**', 'fix/**', 'refactor/**', 'chore/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Copy ConfigProvider for CI
      run: cp src/jvmTest/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt src/jvmMain/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt
    - name: Build with Gradle
      run: ./gradlew test

