name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

      - name: Copy ConfigProvider for CI
        run: cp composeApp/src/commonTest/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt composeApp/src/commonMain/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Xvfb
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Gradle build
        run: xvfb-run ./gradlew build koverXmlReport --no-daemon

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/kover/report.xml
          fail_ci_if_error: true
          verbose: false
