name: Gradle Check on Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Copy ConfigProvider for CI
        run: cp src/jvmTest/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt src/jvmMain/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Gradle build
        run: ./gradlew build --no-daemon

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
