name: Renovate Check

on:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

      - name: Copy ConfigProvider for CI
        run: cp composeApp/src/commonTest/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt composeApp/src/commonMain/kotlin/uk/ryanwong/gmap2ics/app/configs/ProvideConfig.kt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Gradle Check
        run: xvfb-run ./gradlew check
